services:
    - docker:dind
stages:
  - build
  - qa
  - coverage
  - e2e
  - reporting
  - test
  - docker-compose
  - update

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  CODECOV_TOKEN: $CODECOV_TOKEN
  COVERALLS_TOKEN: $COVERALLS_TOKEN
  CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
  RENOVATE_TOKEN: $RENOVATE_TOKEN
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

image: maven:3-openjdk-17
cache:
  paths:
    - .m2/repository

before_script:
  - apt-get update -y
  - apt-get upgrade -y
  - apt-get install build-essential -y
  - bash latest-compose.sh
#  - apt-get install -y docker-compose
#  - apt-get install -y npm
#  - npm install --global yarn
#  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
#  - source ~/.bashrc
#  - nvm install --lts

build-maven:
  image: maven:3.8-openjdk-17-slim
  stage: build
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
  script:
    - make build-maven
  except:
    - schedules

build-front-end:
  image: node:19
  stage: build
  cache:
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  script:
    - make build-npm
  except:
    - schedules

qa-maven:
  image: maven:3.8-openjdk-17-slim
  stage: qa
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
  script:
    - mvn test
  needs:
    - build-maven
  except:
    - schedules

qa-front-end:
  image: node:19
  stage: qa
  cache:
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  script:
    - cd favourite-lyrics-gui && npm test
  needs:
    - build-front-end
  except:
    - schedules

favorite-lyrics-electron-e2e:
  image: node:19
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-electron
  needs:
    - qa-maven
    - qa-front-end
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  allow_failure: true
  timeout: 10m
  except:
    - schedules

favorite-lyrics-chrome-e2e:
  image: node:19
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-chrome
  needs:
    - qa-maven
    - qa-front-end
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  except:
    - schedules

favorite-lyrics-firefox-e2e:
  image: node:19
  stage: e2e
  retry: 2
  allow_failure: true
  script:
    - make dcup-full-action
    - make cypress-firefox
  needs:
    - qa-maven
    - qa-front-end
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  except:
    - schedules

favorite-lyrics-edge-e2e:
  image: node:19
  stage: e2e
  script:
    - make dcup-full-action
    - make cypress-edge
  needs:
    - qa-maven
    - qa-front-end
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  except:
    - schedules

coverage:
  image: maven:3.8-openjdk-17-slim
  stage: coverage
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  script:
    - mvn jacoco:prepare-agent package jacoco:report
  only:
    - master
  needs:
    - build-maven
    - build-front-end
  except:
    - schedules

reporting:
  image: maven:3.8-openjdk-17-slim
  stage: reporting
  cache:
    - key: MAVEN
      paths:
        - favourite-lyrics-core/target/
        - favourite-lyrics-domain/target/
        - favourite-lyrics-jpa/target/
        - favourite-lyrics-rest/target/
        - favourite-lyrics-starter/target/
        - favourite-lyrics-test/target/
    - key: NODE
      paths:
        - favourite-lyrics-gui/build/
        - favourite-lyrics-gui/dist/
        - favourite-lyrics-gui/node_modules/
  script:
    - mvn omni-coveragereporter:report
  only:
    - master
  needs:
    - coverage
    - favorite-lyrics-electron-e2e
    - favorite-lyrics-firefox-e2e
    - favorite-lyrics-chrome-e2e
    - favorite-lyrics-edge-e2e
  except:
    - schedules

update-dependencies:
  image: renovate/renovate
  stage: update
  before_script:
    - ''
  script:
    - export RENOVATE_CONFIG=$(< renovate.json)
    - renovate
  only:
    - schedules
  needs: []

