version: "3.7"
services:
  fla-postgres:
    container_name: ${PROJECT_SLUG}-postgres
    hostname: ${PROJECT_SLUG}-postgres
    restart: on-failure
    image: postgres:15.2
    command: -c 'max_connections=400' -c 'shared_buffers=100MB'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_MULTIPLE_DATABASES}
    volumes:
      - ./docker-images/docker-psql:/docker-entrypoint-initdb.d
      - ./docker-images/docker-psql/multiple:/docker-entrypoint-initdb.d/multiple
    expose:
      - ${PG_EXPOSED_PORT}
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
    networks:
      - fla_net

  fla-backend:
    hostname: ${PROJECT_SLUG}-backend
    container_name: ${PROJECT_SLUG}_backend
    build:
      context: favourite-lyrics-starter/.
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    networks:
      - fla_net

  fla-nginx:
    hostname: ${PROJECT_SLUG}-nginx
    container_name: ${PROJECT_SLUG}-nginx
    build:
      context: ./favourite-lyrics-gui/.
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - FLA_BACKEND=${FLA_BACKEND}
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    env_file:
      - .env
    networks:
      - fla_net

networks:
  fla_net:
